/* ═══════════════════════════════════════════════════════════
   ARCGEN · generators.js — coder executor + file generator
   Emits a complete, dependency-free, playable HTML5 game project
   plus companion ports (C#, C++, Java, Python, GDScript, Rust,
   Lua, GLSL) from the same plan. All strings built locally.
   ═══════════════════════════════════════════════════════════ */
(function (global) {
  'use strict';

  const R = Arc.Planner.rng;

  /* ─────────────────────────────────────────────────────────────
     PLAYABLE CORE — arena shooter / breakout variants
     Written as one self-contained IIFE, seeded & fixed-timestep.
     ───────────────────────────────────────────────────────────── */
  function genGameJS(plan) {
    const r = R(plan.seed ^ 0x9e37);
    const P = plan.palette;
    const waves = Math.max(3, Math.min(20, plan.numbers.waves));
    const mode = plan.genre === 'breakout' ? 'breakout' : 'arena';
    const retro = plan.influence.retro;

    return `/* ${plan.title} — generated by ARCGEN (${plan.slug})
 * genre: ${plan.genre} · seed: ${plan.seed} · target ${plan.numbers.fps}fps
 * Fixed-timestep deterministic loop. No external assets, no network.
 */
(() => {
'use strict';

const CFG = Object.freeze({
  W: 960, H: 540, STEP: 1 / 60,
  SEED: ${plan.seed >>> 0},
  WAVES: ${waves},
  MODE: '${mode}',
  PLAYER_SPEED: ${Math.round(240 + r() * 90)},
  FIRE_COOLDOWN: ${(0.13 + r() * 0.09).toFixed(3)},
  BULLET_SPEED: ${Math.round(520 + r() * 180)},
  ENEMY_BASE: ${Math.round(58 + r() * 34)},
  SHAKE: ${plan.influence.juice.toFixed(2)},
  PAL: [${P.map(c => `'${c}'`).join(', ')}],
  BG: '#060a13',
  PIXELATE: ${retro}
});

/* ---------- seeded rng (mulberry32) ---------- */
let _s = CFG.SEED >>> 0;
function rnd() { _s |= 0; _s = (_s + 0x6D2B79F5) | 0; let t = Math.imul(_s ^ (_s >>> 15), 1 | _s); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }
const rr = (a, b) => a + rnd() * (b - a);
const ri = (a, b) => Math.floor(rr(a, b + 1));
const clamp = (v, a, b) => v < a ? a : v > b ? b : v;
const lerp = (a, b, t) => a + (b - a) * t;

/* ---------- boot ---------- */
const cv = document.getElementById('game');
const cx = cv.getContext('2d');
cv.width = CFG.W; cv.height = CFG.H;
cx.imageSmoothingEnabled = !CFG.PIXELATE;

const hud = {
  score: document.getElementById('hud-score'),
  lives: document.getElementById('hud-lives'),
  wave:  document.getElementById('hud-wave')
};
const banner = document.getElementById('banner');

/* ---------- audio (synth, zero samples) ---------- */
let AC = null;
function sfx(freq, dur, type, vol) {
  try {
    if (!AC) AC = new (window.AudioContext || window.webkitAudioContext)();
    const o = AC.createOscillator(), g = AC.createGain();
    o.type = type || 'square'; o.frequency.value = freq;
    g.gain.setValueAtTime(vol == null ? .05 : vol, AC.currentTime);
    g.gain.exponentialRampToValueAtTime(.0001, AC.currentTime + dur);
    o.connect(g); g.connect(AC.destination); o.start(); o.stop(AC.currentTime + dur);
  } catch (e) { /* audio blocked until gesture — ignore */ }
}

/* ---------- input ---------- */
const keys = Object.create(null);
addEventListener('keydown', e => {
  keys[e.code] = true;
  if (['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)) e.preventDefault();
  if (state.scene === 'menu' && (e.code === 'Space' || e.code === 'Enter')) startRun();
  else if (state.scene === 'over' && e.code === 'KeyR') startRun();
  else if (e.code === 'KeyP' && state.scene !== 'menu') state.paused = !state.paused;
});
addEventListener('keyup', e => { keys[e.code] = false; });
const mouse = { x: CFG.W / 2, y: CFG.H / 2, down: false };
cv.addEventListener('mousemove', e => {
  const b = cv.getBoundingClientRect();
  mouse.x = (e.clientX - b.left) * (CFG.W / b.width);
  mouse.y = (e.clientY - b.top) * (CFG.H / b.height);
});
cv.addEventListener('mousedown', () => { mouse.down = true; if (state.scene === 'menu') startRun(); });
addEventListener('mouseup', () => { mouse.down = false; });
cv.addEventListener('touchmove', e => {
  const b = cv.getBoundingClientRect(), t = e.touches[0];
  mouse.x = (t.clientX - b.left) * (CFG.W / b.width);
  mouse.y = (t.clientY - b.top) * (CFG.H / b.height);
  e.preventDefault();
}, { passive: false });
cv.addEventListener('touchstart', () => { mouse.down = true; if (state.scene === 'menu') startRun(); });
addEventListener('touchend', () => { mouse.down = false; });

/* ---------- world state ---------- */
const state = {
  scene: 'menu', paused: false, t: 0, wave: 0, score: 0, lives: 3,
  shake: 0, flash: 0, hitStop: 0, best: +(localStorage.getItem('${plan.slug}.best') || 0)
};
let player, bullets, enemies, particles, pickups, bricks, ball, paddle;

function makePlayer() {
  return { x: CFG.W / 2, y: CFG.H - 60, r: 13, cd: 0, inv: 0, spread: 0, thrust: 0 };
}

function buildWave(n) {
  const count = 6 + n * 2;
  for (let i = 0; i < count; i++) {
    const kind = rnd();
    enemies.push({
      x: rr(40, CFG.W - 40), y: rr(-260, -30),
      vx: 0, vy: CFG.ENEMY_BASE + n * 7 + rr(-8, 22),
      r: kind > .82 ? 22 : kind > .5 ? 15 : 11,
      hp: kind > .82 ? 3 : kind > .5 ? 2 : 1,
      hue: i % CFG.PAL.length, wob: rr(0, 6.28), amp: rr(0, 70),
      spin: rr(-2, 2), big: kind > .82
    });
  }
}

function buildBricks() {
  const cols = 11, rows = 5 + Math.min(4, state.wave), bw = 74, bh = 24;
  for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) {
    if (rnd() < .08) continue;
    bricks.push({ x: 60 + x * (bw + 6), y: 60 + y * (bh + 6), w: bw, h: bh, hp: rnd() > .82 ? 2 : 1, hue: (x + y) % CFG.PAL.length });
  }
}

function resetBall() {
  ball = { x: paddle.x, y: CFG.H - 70, vx: rr(-160, 160), vy: -330, r: 8, stuck: true };
}

function startRun() {
  state.scene = 'play'; state.wave = 1; state.score = 0; state.lives = 3;
  player = makePlayer(); bullets = []; enemies = []; particles = []; pickups = [];
  bricks = []; paddle = { x: CFG.W / 2, w: 130, h: 14 };
  if (CFG.MODE === 'breakout') { buildBricks(); resetBall(); } else buildWave(1);
  say('WAVE 1'); sfx(660, .12, 'triangle');
}

function say(text, sub) {
  banner.textContent = text + (sub ? ' — ' + sub : '');
  banner.classList.remove('show'); void banner.offsetWidth; banner.classList.add('show');
}

/* ---------- fx ---------- */
function boom(x, y, col, n, power) {
  for (let i = 0; i < n; i++) {
    const a = rr(0, 6.283), sp = rr(40, 260) * (power || 1);
    particles.push({ x, y, vx: Math.cos(a) * sp, vy: Math.sin(a) * sp, life: rr(.25, .7), max: .7, col, size: rr(1.5, 3.6) });
  }
}
function shake(v) { state.shake = Math.min(22, state.shake + v * CFG.SHAKE); }

/* ---------- simulation step ---------- */
function update(dt) {
  state.t += dt;
  if (state.hitStop > 0) { state.hitStop -= dt; return; }
  state.shake *= Math.pow(.0015, dt);
  state.flash = Math.max(0, state.flash - dt * 3);

  if (state.scene !== 'play') return;

  /* particles always alive */
  for (let i = particles.length - 1; i >= 0; i--) {
    const p = particles[i];
    p.x += p.vx * dt; p.y += p.vy * dt; p.vy += 240 * dt; p.vx *= .985;
    p.life -= dt; if (p.life <= 0) particles.splice(i, 1);
  }

  if (CFG.MODE === 'breakout') updateBreakout(dt); else updateArena(dt);

  hud.score.textContent = String(state.score).padStart(6, '0');
  hud.lives.textContent = state.lives;
  hud.wave.textContent = CFG.MODE === 'breakout' ? String(bricks.length) : state.wave + '/' + CFG.WAVES;
}

function updateArena(dt) {
  /* ship movement: keys or pointer follow */
  let dx = (keys.KeyD || keys.ArrowRight ? 1 : 0) - (keys.KeyA || keys.ArrowLeft ? 1 : 0);
  let dy = (keys.KeyS || keys.ArrowDown ? 1 : 0) - (keys.KeyW || keys.ArrowUp ? 1 : 0);
  if (dx || dy) {
    player.x = clamp(player.x + dx * CFG.PLAYER_SPEED * dt, 18, CFG.W - 18);
    player.y = clamp(player.y + dy * CFG.PLAYER_SPEED * dt, 18, CFG.H - 18);
    player.thrust = lerp(player.thrust, 1, dt * 8);
  } else {
    player.x = lerp(player.x, clamp(mouse.x, 18, CFG.W - 18), dt * 9);
    player.y = lerp(player.y, clamp(mouse.y, 18, CFG.H - 18), dt * 9);
    player.thrust = lerp(player.thrust, 0, dt * 6);
  }
  player.cd -= dt; player.inv = Math.max(0, player.inv - dt);

  if ((keys.Space || mouse.down) && player.cd <= 0) {
    player.cd = CFG.FIRE_COOLDOWN;
    const shots = player.spread > 0 ? 3 : 1;
    for (let i = 0; i < shots; i++) {
      const off = (i - (shots - 1) / 2) * .22;
      bullets.push({ x: player.x, y: player.y - 14, vx: Math.sin(off) * CFG.BULLET_SPEED, vy: -Math.cos(off) * CFG.BULLET_SPEED, life: 1.6 });
    }
    sfx(player.spread > 0 ? 880 : 620, .05, 'square', .03);
    if (player.spread > 0) player.spread -= dt;
  }

  for (let i = bullets.length - 1; i >= 0; i--) {
    const b = bullets[i];
    b.x += b.vx * dt; b.y += b.vy * dt; b.life -= dt;
    if (b.life <= 0 || b.y < -20 || b.x < -20 || b.x > CFG.W + 20) bullets.splice(i, 1);
  }

  for (let i = enemies.length - 1; i >= 0; i--) {
    const e = enemies[i];
    e.wob += dt * 2; e.spin += dt;
    e.x += Math.cos(e.wob) * e.amp * dt;
    e.y += e.vy * dt;
    if (e.y > CFG.H + 40) { e.y = -40; e.x = rr(40, CFG.W - 40); }

    for (let j = bullets.length - 1; j >= 0; j--) {
      const b = bullets[j], dxx = b.x - e.x, dyy = b.y - e.y;
      if (dxx * dxx + dyy * dyy < (e.r + 4) * (e.r + 4)) {
        bullets.splice(j, 1); e.hp--;
        boom(b.x, b.y, CFG.PAL[e.hue], 6, .5); sfx(300 + rnd() * 200, .05, 'sawtooth', .03);
        if (e.hp <= 0) {
          state.score += e.big ? 150 : 50;
          boom(e.x, e.y, CFG.PAL[e.hue], e.big ? 40 : 18, e.big ? 1.5 : 1);
          shake(e.big ? 8 : 3); state.hitStop = e.big ? .05 : .015;
          sfx(120, .22, 'sawtooth', .05);
          if (rnd() < .12) pickups.push({ x: e.x, y: e.y, vy: 90, type: rnd() < .5 ? 'spread' : 'life', t: 0 });
          enemies.splice(i, 1);
        }
        break;
      }
    }

    if (enemies[i] === e && player.inv <= 0) {
      const dpx = player.x - e.x, dpy = player.y - e.y;
      if (dpx * dpx + dpy * dpy < (e.r + player.r) * (e.r + player.r)) hurt();
    }
  }

  for (let i = pickups.length - 1; i >= 0; i--) {
    const u = pickups[i]; u.y += u.vy * dt; u.t += dt;
    const dpx = player.x - u.x, dpy = player.y - u.y;
    if (dpx * dpx + dpy * dpy < 26 * 26) {
      if (u.type === 'life') state.lives = Math.min(5, state.lives + 1); else player.spread = 8;
      state.score += 25; boom(u.x, u.y, '#fff', 12, .7); sfx(1200, .1, 'triangle', .05);
      pickups.splice(i, 1);
    } else if (u.y > CFG.H + 20) pickups.splice(i, 1);
  }

  if (!enemies.length) {
    if (state.wave >= CFG.WAVES) endRun(true);
    else { state.wave++; buildWave(state.wave); say('WAVE ' + state.wave); shake(4); sfx(520, .16, 'triangle'); }
  }
}

function hurt() {
  state.lives--; player.inv = 1.4; shake(14); state.flash = 1; state.hitStop = .09;
  boom(player.x, player.y, '#ffffff', 26, 1.3); sfx(90, .3, 'sawtooth', .07);
  if (state.lives <= 0) endRun(false);
}

function updateBreakout(dt) {
  paddle.x = lerp(paddle.x, clamp(mouse.x, paddle.w / 2, CFG.W - paddle.w / 2), dt * 14);
  if (keys.ArrowLeft) paddle.x -= 620 * dt;
  if (keys.ArrowRight) paddle.x += 620 * dt;

  if (ball.stuck) { ball.x = paddle.x; ball.y = CFG.H - 70; if (keys.Space || mouse.down) { ball.stuck = false; sfx(700, .08, 'square'); } return; }

  ball.x += ball.vx * dt; ball.y += ball.vy * dt;
  if (ball.x < ball.r) { ball.x = ball.r; ball.vx *= -1; sfx(500, .04, 'square', .03); }
  if (ball.x > CFG.W - ball.r) { ball.x = CFG.W - ball.r; ball.vx *= -1; sfx(500, .04, 'square', .03); }
  if (ball.y < ball.r + 40) { ball.y = ball.r + 40; ball.vy *= -1; sfx(500, .04, 'square', .03); }

  /* paddle bounce with english */
  if (ball.vy > 0 && ball.y > CFG.H - 62 && ball.y < CFG.H - 40 && Math.abs(ball.x - paddle.x) < paddle.w / 2 + ball.r) {
    const rel = clamp((ball.x - paddle.x) / (paddle.w / 2), -1, 1);
    const speed = Math.min(760, Math.hypot(ball.vx, ball.vy) * 1.035);
    const ang = -Math.PI / 2 + rel * 1.05;
    ball.vx = Math.cos(ang) * speed; ball.vy = Math.sin(ang) * speed;
    sfx(620, .05, 'square', .04); shake(2);
  }

  if (ball.y > CFG.H + 20) {
    state.lives--; shake(12); state.flash = 1; sfx(110, .3, 'sawtooth', .07);
    if (state.lives <= 0) endRun(false); else resetBall();
    return;
  }

  for (let i = bricks.length - 1; i >= 0; i--) {
    const b = bricks[i];
    if (ball.x > b.x - ball.r && ball.x < b.x + b.w + ball.r && ball.y > b.y - ball.r && ball.y < b.y + b.h + ball.r) {
      const ox = Math.min(Math.abs(ball.x - b.x), Math.abs(ball.x - (b.x + b.w)));
      const oy = Math.min(Math.abs(ball.y - b.y), Math.abs(ball.y - (b.y + b.h)));
      if (ox < oy) ball.vx *= -1; else ball.vy *= -1;
      if (--b.hp <= 0) {
        bricks.splice(i, 1); state.score += 30; boom(b.x + b.w / 2, b.y + b.h / 2, CFG.PAL[b.hue], 14, .9);
        shake(3); sfx(340 + rnd() * 260, .06, 'square', .04);
      } else { state.score += 5; sfx(240, .04, 'square', .03); }
      break;
    }
  }
  if (!bricks.length) {
    if (state.wave >= 4) endRun(true);
    else { state.wave++; buildBricks(); resetBall(); say('FIELD ' + state.wave); }
  }
}

function endRun(won) {
  state.scene = 'over'; state.won = won;
  if (state.score > state.best) { state.best = state.score; localStorage.setItem('${plan.slug}.best', String(state.best)); }
  say(won ? 'MISSION CLEAR' : 'RUN OVER', 'press R to retry');
  sfx(won ? 880 : 140, .5, won ? 'triangle' : 'sawtooth', .06);
}

/* ---------- render ---------- */
function drawShip() {
  const p = player;
  cx.save(); cx.translate(p.x, p.y);
  if (p.inv > 0 && Math.floor(state.t * 14) % 2) cx.globalAlpha = .35;
  const flame = 8 + p.thrust * 16 + Math.sin(state.t * 40) * 3;
  cx.fillStyle = CFG.PAL[2]; cx.beginPath();
  cx.moveTo(-5, 10); cx.lineTo(0, 10 + flame); cx.lineTo(5, 10); cx.closePath(); cx.fill();
  cx.fillStyle = CFG.PAL[1]; cx.beginPath();
  cx.moveTo(0, -18); cx.lineTo(13, 12); cx.lineTo(0, 6); cx.lineTo(-13, 12); cx.closePath(); cx.fill();
  cx.fillStyle = '#fff'; cx.beginPath(); cx.arc(0, -2, 3, 0, 6.283); cx.fill();
  cx.restore();
}

function drawEnemy(e) {
  cx.save(); cx.translate(e.x, e.y); cx.rotate(e.spin);
  cx.strokeStyle = CFG.PAL[e.hue]; cx.lineWidth = 2.5; cx.fillStyle = 'rgba(255,255,255,.06)';
  const sides = e.big ? 6 : e.r > 13 ? 4 : 3, rad = e.r;
  cx.beginPath();
  for (let i = 0; i < sides; i++) {
    const a = i / sides * 6.283;
    i ? cx.lineTo(Math.cos(a) * rad, Math.sin(a) * rad) : cx.moveTo(Math.cos(a) * rad, Math.sin(a) * rad);
  }
  cx.closePath(); cx.fill(); cx.stroke();
  cx.restore();
}

function render() {
  const sx = state.shake ? rr(-state.shake, state.shake) : 0;
  const sy = state.shake ? rr(-state.shake, state.shake) : 0;
  cx.setTransform(1, 0, 0, 1, sx, sy);
  cx.fillStyle = CFG.BG; cx.fillRect(-30, -30, CFG.W + 60, CFG.H + 60);

  /* starfield / grid backdrop */
  cx.strokeStyle = 'rgba(122,162,255,.07)'; cx.lineWidth = 1;
  const gs = CFG.PIXELATE ? 30 : 46, off = (state.t * 26) % gs;
  for (let x = -gs; x < CFG.W + gs; x += gs) { cx.beginPath(); cx.moveTo(x, 0); cx.lineTo(x, CFG.H); cx.stroke(); }
  for (let y = -gs; y < CFG.H + gs; y += gs) { cx.beginPath(); cx.moveTo(0, y + off); cx.lineTo(CFG.W, y + off); cx.stroke(); }

  if (state.scene === 'menu') {
    cx.fillStyle = CFG.PAL[1]; cx.textAlign = 'center';
    cx.font = '700 46px "Space Grotesk", system-ui, sans-serif';
    cx.fillText('${plan.title}', CFG.W / 2, CFG.H / 2 - 34);
    cx.fillStyle = 'rgba(232,238,252,.6)'; cx.font = '14px "JetBrains Mono", monospace';
    cx.fillText('WASD / arrows move · SPACE or CLICK fires · P pause', CFG.W / 2, CFG.H / 2 + 8);
    cx.fillStyle = CFG.PAL[0];
    cx.fillText('PRESS SPACE TO LAUNCH', CFG.W / 2, CFG.H / 2 + 44);
    cx.fillStyle = 'rgba(147,163,196,.55)';
    cx.fillText('BEST ' + state.best, CFG.W / 2, CFG.H / 2 + 74);
    return;
  }

  /* entities */
  if (CFG.MODE === 'breakout') {
    cx.fillStyle = CFG.PAL[0];
    for (const b of bricks) {
      cx.globalAlpha = b.hp > 1 ? 1 : .78; cx.fillStyle = CFG.PAL[b.hue];
      cx.fillRect(b.x, b.y, b.w, b.h);
      cx.fillStyle = 'rgba(255,255,255,.16)'; cx.fillRect(b.x, b.y, b.w, 3);
    }
    cx.globalAlpha = 1;
    cx.fillStyle = '#e8eefc'; cx.fillRect(paddle.x - paddle.w / 2, CFG.H - 56, paddle.w, paddle.h);
    cx.beginPath(); cx.arc(ball.x, ball.y, ball.r, 0, 6.283); cx.fillStyle = CFG.PAL[1]; cx.fill();
  } else {
    cx.fillStyle = '#fff';
    for (const b of bullets) { cx.fillRect(b.x - 1.6, b.y - 8, 3.2, 12); }
    for (const u of pickups) {
      cx.save(); cx.translate(u.x, u.y); cx.rotate(u.t * 3);
      cx.fillStyle = u.type === 'life' ? CFG.PAL[3] : CFG.PAL[2];
      cx.fillRect(-7, -7, 14, 14); cx.restore();
    }
    for (const e of enemies) drawEnemy(e);
    drawShip();
  }

  for (const p of particles) {
    cx.globalAlpha = clamp(p.life / p.max, 0, 1);
    cx.fillStyle = p.col; cx.fillRect(p.x - p.size / 2, p.y - p.size / 2, p.size, p.size);
  }
  cx.globalAlpha = 1;

  if (state.flash > 0) { cx.fillStyle = 'rgba(255,90,90,' + (state.flash * .28) + ')'; cx.fillRect(0, 0, CFG.W, CFG.H); }

  if (state.scene === 'over') {
    cx.fillStyle = 'rgba(4,7,14,.72)'; cx.fillRect(0, 0, CFG.W, CFG.H);
    cx.textAlign = 'center'; cx.fillStyle = state.won ? CFG.PAL[1] : CFG.PAL[0];
    cx.font = '700 42px "Space Grotesk", system-ui, sans-serif';
    cx.fillText(state.won ? 'MISSION CLEAR' : 'RUN OVER', CFG.W / 2, CFG.H / 2 - 16);
    cx.fillStyle = '#e8eefc'; cx.font = '16px "JetBrains Mono", monospace';
    cx.fillText('SCORE ' + state.score + '   BEST ' + state.best, CFG.W / 2, CFG.H / 2 + 22);
    cx.fillStyle = 'rgba(147,163,196,.8)'; cx.font = '13px "JetBrains Mono", monospace';
    cx.fillText('press R to redeploy', CFG.W / 2, CFG.H / 2 + 52);
  }

  if (state.paused && state.scene === 'play') {
    cx.fillStyle = 'rgba(4,7,14,.6)'; cx.fillRect(0, 0, CFG.W, CFG.H);
    cx.fillStyle = CFG.PAL[2]; cx.textAlign = 'center'; cx.font = '700 30px "Space Grotesk", sans-serif';
    cx.fillText('PAUSED', CFG.W / 2, CFG.H / 2);
  }
}

/* ---------- fixed timestep driver ---------- */
let acc = 0, last = performance.now(), fpsT = last, frames = 0;
function frame(now) {
  requestAnimationFrame(frame);
  let dt = (now - last) / 1000; last = now;
  if (dt > .25) dt = .25;
  acc += dt;
  while (acc >= CFG.STEP) { update(CFG.STEP); acc -= CFG.STEP; }
  render();
  frames++;
  if (now - fpsT > 500) {
    const fps = Math.round(frames * 1000 / (now - fpsT));
    parent.postMessage({ arcgen: 'perf', fps, ms: +(1000 / Math.max(1, fps)).toFixed(1), sprites: particles.length + enemies.length + bullets.length + bricks.length }, '*');
    frames = 0; fpsT = now;
  }
}
requestAnimationFrame(frame);
})();`;
  }

  /* ─────────── HTML shell ───────────
     The HUD stylesheet is INLINED into index.html so the game is
     self-contained: the srcdoc iframe preview and a downloaded copy
     both render with zero sibling-file fetches (no black screen).
     css/hud.css is still emitted as the canonical source of truth. */
  function genIndexHTML(plan) {
    const g = plan.genreLabel;
    const hud = genHudCSS(plan);
    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${plan.title} — built by ARCGEN</title>
<style>
${hud}
</style>
</head>
<body class="mode-${plan.view}">
<header class="hud">
  <div class="hud-cell"><label>SCORE</label><b id="hud-score">000000</b></div>
  <div class="hud-cell"><label>LIVES</label><b id="hud-lives">3</b></div>
  <div class="hud-cell"><label>${g.hud[2]}</label><b id="hud-wave">1</b></div>
  <div class="hud-title">${plan.title}</div>
</header>

<main class="stage">
  <canvas id="game" width="960" height="540" aria-label="${plan.title} game canvas"></canvas>
  <div id="banner" class="banner" role="status"></div>
</main>

<footer class="foot">
  <span>${g.tagline}</span><span>·</span>
  <span>win: ${plan.win}</span><span>·</span>
  <span>seed ${plan.seed >>> 0}</span>
</footer>

<script src="js/game.js"></script>
</body>
</html>`;
  }

  /* ─────────── CSS HUD ─────────── */
  function genHudCSS(plan) {
    const P = plan.palette;
    return `/* ${plan.title} HUD — generated by ARCGEN */
:root{
  --p0:${P[0]}; --p1:${P[1]}; --p2:${P[2]}; --p3:${P[3] || P[0]};
  --bg:#060a13; --ink:#e8eefc; --dim:#93a3c4;
  --grid: rgba(122,162,255,.06);
}
*{box-sizing:border-box}
html,body{height:100%;margin:0}
body{
  background:
    radial-gradient(900px 500px at 50% -10%, rgba(139,107,255,.16), transparent 70%),
    linear-gradient(var(--grid) 1px, transparent 1px) 0 0/100% 46px,
    var(--bg);
  color:var(--ink); font-family:"Space Grotesk",system-ui,sans-serif;
  display:flex; flex-direction:column; overflow:hidden;
}
.hud{display:flex;align-items:center;gap:22px;padding:10px 18px;border-bottom:1px solid rgba(122,162,255,.16)}
.hud-cell{display:flex;flex-direction:column;line-height:1.15}
.hud-cell label{font-size:9px;letter-spacing:.18em;color:var(--dim);font-family:"JetBrains Mono",monospace}
.hud-cell b{font-family:"JetBrains Mono",monospace;font-size:18px;color:var(--p1);text-shadow:0 0 14px var(--p1)}
.hud-title{margin-left:auto;font-weight:700;letter-spacing:.24em;font-size:12px;color:var(--dim);text-transform:uppercase}
.stage{flex:1;display:grid;place-items:center;position:relative;padding:10px;min-height:0}
canvas#game{
  width:min(100%, calc((100vh - 130px) * 16 / 9));
  aspect-ratio:16/9; display:block; background:#000; border-radius:10px;
  border:1px solid rgba(122,162,255,.28);
  box-shadow:0 0 0 1px rgba(0,0,0,.6),0 30px 70px -30px #000,0 0 70px -24px var(--p0);
  cursor:crosshair; touch-action:none;
${plan.influence.retro ? '  image-rendering:pixelated;' : ''}}
.banner{
  position:absolute;top:16%;left:50%;transform:translateX(-50%) scale(.9);
  font-family:"JetBrains Mono",monospace;font-size:clamp(16px,3vw,26px);letter-spacing:.22em;
  color:var(--p2);text-shadow:0 0 22px var(--p2);opacity:0;pointer-events:none;white-space:nowrap;
}
.banner.show{animation:pop 1.5s ease-out}
@keyframes pop{0%{opacity:0;transform:translateX(-50%) scale(.7)}18%{opacity:1;transform:translateX(-50%) scale(1.12)}70%{opacity:1}100%{opacity:0;transform:translateX(-50%) scale(1)}}
.foot{display:flex;gap:12px;justify-content:center;padding:8px;font-family:"JetBrains Mono",monospace;font-size:10px;color:#5d6b8c;border-top:1px solid rgba(122,162,255,.12)}
@media (max-width:640px){.hud{gap:14px}.hud-title{display:none}}`;
  }

  /* ─────────── GDD markdown ─────────── */
  function genGDD(plan) {
    const g = plan.genreLabel;
    return `# ${plan.title}
> ${g.tagline} · genre \`${plan.genre}\` · view \`${plan.view}\` · seed \`${plan.seed >>> 0}\`
> directive: *"${plan.brief}"*

## 1 · Core fantasy
${plan.pillars.map(p => '- ' + p).join('\n')}

## 2 · Game loop
| beat | duration | verb | feedback |
|---|---|---|---|
| read | 0.2–0.6 s | scan field | palette-coded silhouettes |
| act  | instant   | ${g.mechanics[0]} | muzzle/paddle impulse + blip |
| react| 0.3 s     | dodge / aim | hit-stop, screen shake |
| reward| 1 s      | score tick | particle burst, HUD pop |

**Win:** ${plan.win}  ·  **Lose:** ${plan.lose}  ·  **Spawn:** ${plan.spawn}

## 3 · Systems
${plan.systems.map(s => `- **${s.name}** — ${s.desc}`).join('\n')}

## 4 · Entities
${g.entities.map(e => '- ' + e).join('\n')}

## 5 · Mechanics stack
${g.mechanics.map(m => '- ' + m).join('\n')}

## 6 · Tuning block (edit freely, no code changes needed)
\`\`\`js
CFG = {
  PLAYER_SPEED : ~${280},       // px/s
  FIRE_COOLDOWN: ~0.17,         // s between shots
  BULLET_SPEED : ~600,          // px/s
  ENEMY_BASE   : ~${plan.numbers.waves * 6 + 50},           // px/s descent
  WAVES        : ${plan.numbers.waves},
  STEP         : 1/60,          // fixed timestep — determinism lock
  SHAKE        : ${plan.influence.juice.toFixed(2)}
}
\`\`\`

## 7 · Art direction
palette \`${plan.palette.join(' · ')}\` on \`#060a13\`. Vector primitives only —
zero binary assets so the whole game fits in one folder and loads offline.
${plan.influence.retro ? 'Pixel-locked rendering, \`image-rendering: pixelated\`, CRT-friendly contrast.' : 'Glow accents via shadowBlur-equivalent post pass (see shader/crt.glsl).'}

## 8 · Audio
Procedural WebAudio blips (square/tri/saw). No sample files → no licensing risk, tiny bundle.

## 9 · Performance budget
≤ ${plan.budget.frameMs} ms/frame · ≤ ${plan.budget.maxSprites} live sprites · ≤ ${plan.budget.bundleKb} KB total source.

## 10 · Ports included
${['JavaScript runtime (playable)', 'C# Unity component', 'C++ Unreal actor', 'Java LibGDX screen', 'Python pygame prototype', 'GDScript Godot 4', 'Rust/WASM sim core', 'GLSL post shader', 'Lua mod API'].map(x => '- ' + x).join('\n')}
`;
  }

  /* ─────────── architecture json ─────────── */
  function genArchJSON(plan) {
    return JSON.stringify({
      name: plan.slug, title: plan.title, engine: 'arcgen-canvas-2d', version: '1.0.0',
      genre: plan.genre, view: plan.view, seed: plan.seed >>> 0,
      targetFPS: plan.numbers.fps, timestep: 'fixed-1/60',
      modules: plan.systems.map(s => ({ id: s.name.toLowerCase(), doc: s.desc })),
      entities: plan.genreLabel.entities,
      scenes: ['Menu', 'Play', 'Paused', 'GameOver'],
      input: { move: ['KeyW', 'KeyA', 'KeyS', 'KeyD', 'Arrows', 'pointer'], fire: ['Space', 'Mouse0'], pause: 'KeyP', retry: 'KeyR' },
      data: { waves: plan.numbers.waves, palette: plan.palette, budget: plan.budget },
      persistence: { key: plan.slug + '.best', value: 'highscore:int' },
      personaDigest: plan.personaDigest,
      buildTargets: ['web', 'unity', 'unreal', 'godot', 'libgdx', 'pygame', 'wasm']
    }, null, 2);
  }

  /* ─────────── C# (Unity) port ─────────── */
  function genUnityCS(plan) {
    return `// ${plan.title} — Unity port generated by ARCGEN
// Drop into Assets/Scripts/. Requires Rigidbody2D + Collider2D on Player.
using System.Collections;
using UnityEngine;

namespace ArcGen.${plan.genre.toUpperCase()}
{
    [CreateAssetMenu(menuName = "ArcGen/" + nameof(TuningTable))]
    public sealed class TuningTable : ScriptableObject
    {
        public float moveSpeed = ${Math.round(6 + plan.influence.juice * 2)}f;
        public float jumpImpulse = 14f;
        public float fireCooldown = ${plan.influence.retro ? '.18f' : '.17f'};
        public int waves = ${plan.numbers.waves};
        public Color[] palette = new Color[] { ${plan.palette.map(hex2unity).join(', ')} };
    }

    [RequireComponent(typeof(Rigidbody2D))]
    public sealed class PlayerController : MonoBehaviour
    {
        [SerializeField] private TuningTable tuning;
        [SerializeField] private Bullet bulletPrefab;
        [SerializeField] private Transform muzzle;

        private Rigidbody2D _rb;
        private bool _grounded;
        private float _nextShot;
        private int _coyoteFrames = 6;   // forgiveness window
        private int _airJumps = 1;

        private void Awake() => _rb = GetComponent<Rigidbody2D>();

        private void Update()
        {
            _grounded = Physics2D.Raycast(transform.position, Vector2.down, 1.05f, LayerMask.GetMask("Ground"));
            HandleMove();
            HandleJump();
            HandleFire();
        }

        private void HandleMove()
        {
            float axis = Input.GetAxisRaw("Horizontal");
            Vector2 v = _rb.velocity;
            v.x = Mathf.MoveTowards(v.x, axis * tuning.moveSpeed, 60f * Time.fixedDeltaTime);
            _rb.velocity = v;
            if (axis != 0f) transform.localScale = new Vector2(Mathf.Sign(axis), 1f);
        }

        private void HandleJump()
        {
            if (!Input.GetButtonDown("Jump")) return;
            if (_grounded || _coyoteFrames-- > 0)
            {
                _rb.velocity = new Vector2(_rb.velocity.x, tuning.jumpImpulse);
                FX.Shake(0.18f); AudioBlip.Play(520f);
            }
            else if (_airJumps-- > 0)
            {
                _rb.velocity = new Vector2(_rb.velocity.x, tuning.jumpImpulse * 0.86f);
                FX.SpawnDust(transform.position, tuning.palette[1]);
            }
            if (_grounded) _coyoteFrames = 6;
        }

        private void HandleFire()
        {
            if (Time.time < _nextShot || !Input.GetButton("Fire1")) return;
            _nextShot = Time.time + tuning.fireCooldown;
            var b = Pool.Spawn(bulletPrefab, muzzle.position, muzzle.rotation);
            b.Fire(Vector2.up * 24f);
            AudioBlip.Play(760f, 0.05f);
        }

        private void OnCollisionEnter2D(Collision2D c)
        {
            if (c.gameObject.CompareTag("Hazard")) Kill();
        }

        public void Kill()
        {
            FX.Shake(0.6f); Score.Lives--;
            if (Score.Lives <= 0) SceneFlow.GameOver();
            else SceneFlow.Respawn();
        }
    }

    public sealed class Bullet : MonoBehaviour
    {
        private Vector2 _vel;
        private float _ttl = 2f;
        public void Fire(Vector2 velocity) { _vel = velocity; gameObject.SetActive(true); }
        private void Update()
        {
            transform.position += (Vector3)(_vel * Time.deltaTime);
            if ((_ttl -= Time.deltaTime) <= 0f) Pool.Despawn(this);
        }
        private void OnTriggerEnter2D(Collider2D other)
        {
            if (other.CompareTag("Enemy")) { other.GetComponent<Enemy>()?.Hit(1); Pool.Despawn(this); }
        }
    }
}`;
  }

  /* ─────────── C++ (Unreal-style) port ─────────── */
  function genUnrealCPP(plan) {
    return `// ${plan.title} — Unreal-style module generated by ARCGEN
// AGameModeBase subclass + physics-driven player pawn.
#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "Components/SphereComponent.h"
#include "Kismet/GameplayStatics.h"
#include "${plan.title.replace(/[^A-Za-z0-9]/g, '')}Pawn.generated.h"

UCLASS()
class AUfoPawn : public ACharacter
{
    GENERATED_BODY()
public:
    UPROPERTY(EditAnywhere, Category = "ArcGen|Tuning")
    float MaxSpeed = ${Math.round(600 + plan.influence.juice * 120)}.f;

    UPROPERTY(EditAnywhere, Category = "ArcGen|Tuning")
    float BoostChargeRate = 1.35f;

    UPROPERTY(EditAnywhere, Category = "ArcGen|Tuning")
    int32 WaveCount = ${plan.numbers.waves};

    UPROPERTY(BlueprintReadOnly, Category = "ArcGen|State")
    float DriftMeter = 0.f;

protected:
    virtual void BeginPlay() override
    {
        Super::BeginPlay();
        GetMesh()->SetAnimInstanceClass(nullptr);
        RootCollision->SetCollisionProfileName(TEXT("Pawn"));
        UE_LOG(LogTemp, Display, TEXT("[ARCGEN] ${plan.title} boot seed=%d"), ${plan.seed >>> 0});
    }

    virtual void SetupPlayerInputComponent(UInputComponent* In) override
    {
        Super::SetupPlayerInputComponent(In);
        In->BindAxisAction("Move", this, &AUfoPawn::OnMove);
        In->BindAction("Drift", IE_Pressed, this, &AUfoPawn::BeginDrift);
        In->BindAction("Drift", IE_Released, this, &AUfoPawn::EndDrift);
        In->BindAction("Boost", IE_Pressed, this, &AUfoPawn::ReleaseBoost);
    }

private:
    UPROPERTY() USphereComponent* RootCollision = CreateDefaultSubobject<USphereComponent>(TEXT("RootCol"));

    bool bDrifting = false;
    FVector LastVel = FVector::ZeroVector;

    void OnMove(const FInputActionValue& V)
    {
        const FVector2D Axis = V.Get<FVector2D>();
        AddMovementInput(GetActorForwardVector(), Axis.Y);
        AddMovementInput(GetActorRightVector(),  Axis.X);
    }

    void BeginDrift()
    {
        bDrifting = true;
        GetWorld()->GetFirstPlayerController()->ClientPlayCameraShake(DriftShake, 1.f);
    }

    void EndDrift()
    {
        bDrifting = false;
        DriftMeter = FMath::Clamp(DriftMeter + LateralSlipRatio() * 0.4f, 0.f, 1.f);
    }

    void ReleaseBoost()
    {
        if (DriftMeter < 0.6f) return;
        LaunchCharacter(GetActorForwardVector() * MaxSpeed * (1.f + DriftMeter), true, false);
        DriftMeter = 0.f;
        SpawnBurst(GetActorLocation(), FLinearColor(${plan.palette[0].slice(1).match(/../g).map(h => '(int)' + parseInt(h, 16) + '/255.f').join(', ')}), 64);
    }

    float LateralSlipRatio() const
    {
        const FVector V = GetVelocity();
        if (V.SizeSquared() < 1.f) return 0.f;
        return FMath::Abs(FVector::DotProduct(V.GetSafeNormal(), GetActorRightVector()));
    }

    void SpawnBurst(const FVector& Loc, const FLinearColor& Col, int32 Count);
    TSubclassOf<UCameraShakeBase> DriftShake;
};`;
  }

  /* ─────────── Java (LibGDX) ─────────── */
  function genJava(plan) {
    return `// ${plan.title} — LibGDX desktop/Android port generated by ARCGEN
package com.arcgen.${plan.slug.replace(/-/g, '_')};

import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.math.MathUtils;
import com.badlogic.gdx.math.Vector2;
import java.util.ArrayList;
import java.util.List;

public final class ${className(plan.title)} extends ApplicationAdapter {
    /** Deterministic RNG keeps replays byte-identical across platforms. */
    private static final long SEED = ${plan.seed >>> 0}L;
    private static final float STEP = 1f / 60f;
    private static final int WAVE_TARGET = ${plan.numbers.waves};

    private OrthographicCamera cam;
    private ShapeRenderer sr;
    private final List<Drone> drones = new ArrayList<>();
    private final Vector2 ship = new Vector2(480f, 90f);
    private float acc, cooldown, waveTimer;
    private int wave = 1, score = 0, lives = 3;
    private long bits = SEED;

    @Override public void create() {
        cam = new OrthographicCamera(960f, 540f);
        cam.position.set(480f, 270f, 0f);
        sr = new ShapeRenderer();
        Gdx.app.log("ARCGEN", "${plan.title} ready · seed " + SEED);
    }

    private float rnd() { // xorshift64
        bits ^= bits << 13; bits ^= bits >>> 7; bits ^= bits << 17;
        return (bits & 0x7FFFFFFF) / (float) 0x7FFFFFFF;
    }

    @Override public void render() {
        acc += Math.min(Gdx.graphics.getDeltaTime(), 0.25f);
        while (acc >= STEP) { update(STEP); acc -= STEP; }
        Gdx.gl.glClearColor(0.024f, 0.039f, 0.075f, 1f);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        sr.setProjectionMatrix(cam.combined);
        draw();
    }

    private void update(float dt) {
        float ax = (Gdx.input.isKeyPressed(Input.Keys.D) ? 1 : 0) - (Gdx.input.isKeyPressed(Input.Keys.A) ? 1 : 0);
        float ay = (Gdx.input.isKeyPressed(Input.Keys.S) ? 1 : 0) - (Gdx.input.isKeyPressed(Input.Keys.W) ? 1 : 0);
        ship.x = MathUtils.clamp(ship.x + ax * 300f * dt, 16f, 944f);
        ship.y = MathUtils.clamp(ship.y + ay * 300f * dt, 16f, 524f);

        cooldown -= dt;
        if (Gdx.input.isKeyPressed(Input.Keys.SPACE) && cooldown <= 0f) {
            cooldown = 0.17f; score += 1;
        }
        waveTimer -= dt;
        if (drones.isEmpty() && waveTimer <= 0f) { spawnWave(); waveTimer = 1.2f; }
        for (int i = drones.size() - 1; i >= 0; i--) {
            Drone d = drones.get(i);
            d.y -= d.speed * dt; d.x += MathUtils.sin(d.phase += dt * 2f) * d.sway * dt;
            if (d.hits(ship)) { drones.remove(i); if (--lives <= 0) reset(); }
            else if (d.y < -40f) d.y = 580f;
        }
    }

    private void spawnWave() {
        if (wave > WAVE_TARGET) { reset(); return; }
        for (int i = 0; i < 6 + wave * 2; i++) {
            Drone d = new Drone();
            d.x = 40f + rnd() * 880f; d.y = 560f + rnd() * 220f;
            d.speed = 60f + wave * 7f + rnd() * 20f;
            d.sway = rnd() * 70f;
            drones.add(d);
        }
        wave++;
    }

    private void reset() { wave = 1; lives = 3; score = 0; drones.clear(); ship.set(480f, 90f); }

    private void draw() {
        sr.begin(ShapeRenderer.ShapeType.Filled);
        sr.setColor(0.208f, 0.949f, 0.843f, 1f);
        sr.circle(ship.x, ship.y, 13f);
        sr.setColor(1f, 0.24f, 0.506f, 1f);
        for (Drone d : drones) sr.rect(d.x - 10f, d.y - 10f, 20f, 20f);
        sr.end();
    }

    static final class Drone {
        float x, y, speed, sway, phase;
        boolean hits(Vector2 p) { return Math.abs(x - p.x) < 22f && Math.abs(y - p.y) < 22f; }
    }

    private static String className(String s) { return s; }
}`;
  }

  /* ─────────── Python (pygame) ─────────── */
  function genPython(plan) {
    return `"""${plan.title} — pygame prototype generated by ARCGEN
Run:  pip install pygame && python src/main.py
Deterministic: same seed -> identical enemy script.
"""
from __future__ import annotations
import math, random, sys
import pygame

SEED        = ${plan.seed >>> 0}
STEP        = 1 / 60
WAVE_TARGET = ${plan.numbers.waves}
SIZE        = (960, 540)
PAL         = [${plan.palette.map(pycolor).join(', ')}]
BG          = (6, 10, 19)


class Ship:
    def __init__(self) -> None:
        self.pos = pygame.Vector2(SIZE[0] / 2, SIZE[1] - 60)
        self.speed = ${Math.round(240 + plan.influence.juice * 40)}
        self.cooldown = 0.0
        self.invuln = 0.0

    def update(self, dt: float, keys) -> list[pygame.Vector2]:
        shots: list[pygame.Vector2] = []
        dx = (keys[pygame.K_d] or keys[pygame.K_RIGHT]) - (keys[pygame.K_a] or keys[pygame.K_LEFT])
        dy = (keys[pygame.K_s] or keys[pygame.K_DOWN]) - (keys[pygame.K_w] or keys[pygame.K_UP])
        self.pos.x = max(16, min(SIZE[0] - 16, self.pos.x + dx * self.speed * dt))
        self.pos.y = max(16, min(SIZE[1] - 16, self.pos.y + dy * self.speed * dt))
        self.cooldown -= dt
        self.invuln = max(0.0, self.invuln - dt)
        if keys[pygame.K_SPACE] and self.cooldown <= 0:
            self.cooldown = 0.17
            shots.append(self.pos.copy())
        return shots

    def draw(self, surf: pygame.Surface) -> None:
        if self.invuln > 0 and int(self.invuln * 14) % 2:
            return
        p, c = self.pos, PAL[1]
        pygame.draw.polygon(surf, c, [(p.x, p.y - 18), (p.x + 13, p.y + 12), (p.x, p.y + 6), (p.x - 13, p.y + 12)])


class Drone:
    def __init__(self, rng: random.Random, wave: int) -> None:
        self.pos = pygame.Vector2(rng.uniform(40, SIZE[0] - 40), rng.uniform(-260, -30))
        self.speed = ${Math.round(plan.numbers.waves * 6 + 50)} + wave * 7 + rng.uniform(-8, 22)
        self.radius = rng.choice([11, 15, 22])
        self.color = PAL[rng.randrange(len(PAL))]
        self.phase = rng.uniform(0, math.tau)
        self.sway = rng.uniform(0, 70)

    def update(self, dt: float) -> None:
        self.phase += dt * 2
        self.pos.x += math.cos(self.phase) * self.sway * dt
        self.pos.y += self.speed * dt
        if self.pos.y > SIZE[1] + 40:
            self.pos.y = -40


def main() -> int:
    pygame.init()
    screen = pygame.display.set_mode(SIZE)
    clock = pygame.time.Clock()
    rng = random.Random(SEED)
    ship, drones, bullets = Ship(), [], []
    score, lives, wave, acc = 0, 3, 1, 0.0
    font = pygame.font.SysFont("jetbrainsmono,consolas", 16)

    def spawn(w: int) -> None:
        drones.extend(Drone(rng, w) for _ in range(6 + w * 2))

    spawn(wave)
    running = True
    while running:
        for ev in pygame.event.get():
            if ev.type == pygame.QUIT:
                running = False
            if ev.type == pygame.KEYDOWN and ev.key == pygame.K_r and lives <= 0:
                score, lives, wave = 0, 3, 1
                ship.__init__(); drones.clear(); spawn(wave)

        acc += min(clock.tick(240) / 1000, 0.25)
        while acc >= STEP:                      # fixed timestep lock
            acc -= STEP
            keys = pygame.key.get_pressed()
            bullets.extend(ship.update(STEP, keys) for _ in [0]) if False else None
            for origin in ship.update(STEP, keys):
                bullets.append([origin.x, origin.y - 14])
            for b in bullets:
                b[1] -= 600 * STEP
            bullets = [b for b in bullets if b[1] > -20]
            for d in drones:
                d.update(STEP)
                if ship.invuln <= 0 and d.pos.distance_to(ship.pos) < d.radius + 13:
                    lives -= 1; ship.invuln = 1.4
            hit = {(i, j) for i, d in enumerate(drones) for j, b in enumerate(bullets)
                   if (b[0] - d.pos.x) ** 2 + (b[1] - d.pos.y) ** 2 < (d.radius + 4) ** 2}
            for i, j in sorted(hit, key=lambda p: (p[1], p[0]), reverse=True):
                del bullets[j]
                drones[i].radius -= 3
                if drones[i].radius < 8:
                    score += 50; del drones[i]
            if not drones:
                wave += 1
                if wave > WAVE_TARGET:
                    score += 1000; wave = WAVE_TARGET; drones.clear(); spawn(wave)
                else:
                    spawn(wave)

        screen.fill(BG)
        for d in drones:
            pygame.draw.circle(screen, d.color, d.pos, max(4, d.radius))
        for b in bullets:
            pygame.draw.rect(screen, (255, 255, 255), (b[0] - 2, b[1] - 8, 4, 12))
        ship.draw(screen)
        screen.blit(font.render(f"SCORE {score:06d}  WAVE {wave}/{WAVE_TARGET}  LIVES {lives}", True, PAL[1]), (14, 10))
        pygame.display.flip()

    pygame.quit()
    return 0


if __name__ == "__main__":
    sys.exit(main())`;
  }

  /* ─────────── GDScript (Godot 4) ─────────── */
  function genGDScript(plan) {
    return `# ${plan.title} — Godot 4 port generated by ARCGEN
# Attach to a CharacterBody2D node; wire "move"/"fire" in Project Settings.
extends CharacterBody2D

const SPEED := ${Math.round(260 + plan.influence.juice * 30)}.0
const JUMP_VELOCITY := -430.0
const COYOTE := 0.12
const WAVES := ${plan.numbers.waves}
@export var bullet_scene: PackedScene
@export var palette: Array[Color] = [${plan.palette.map(godotcolor).join(', ')}]

var _coyote_t: float = 0.0
var _fire_cd: float = 0.0
var _wave: int = 1
var _rng := RandomNumberGenerator.new()

func _ready() -> void:
	_rng.seed = ${plan.seed >>> 0}
	print("[ARCGEN] ${plan.title} · godot4 · seed ", _rng.seed)

func _physics_process(delta: float) -> void:
	var grounded := is_on_floor()
	_coyote_t = COYOTE if grounded else maxf(_coyote_t - delta, 0.0)

	if not grounded:
		velocity.y += ProjectSettings.get_setting("physics/2d/default_gravity") * delta

	var dir := Input.get_axis("move_left", "move_right")
	if dir:
		velocity.x = move_toward(velocity.x, dir * SPEED, SPEED * 6.0 * delta)
		$Sprite2D.flip_h = dir < 0.0
	else:
		velocity.x = move_toward(velocity.x, 0.0, SPEED * 10.0 * delta)

	if Input.is_action_just_pressed("jump") and (_coyote_t > 0.0 or _has_air_jump()):
		velocity.y = JUMP_VELOCITY
		_coyote_t = 0.0
		_shake(0.15)

	_fire_cd -= delta
	if Input.is_action_pressed("fire") and _fire_cd <= 0.0:
		_fire_cd = 0.17
		_spawn_bullet()

	move_and_slide()

func _spawn_bullet() -> void:
	var b := bullet_scene.instantiate()
	b.global_position = $Muzzle.global_position
	get_parent().add_child(b)
	AudioBlip.play(740.0)

func _shake(amount: float) -> void:
	var cam := get_viewport().get_camera_2d()
	if cam: cam.offset = Vector2(_rng.randf_range(-amount, amount) * 20.0, 0.0)

func _has_air_jump() -> bool: return _wave < WAVES

func _on_area_entered(area: Area2D) -> void:
	if area.is_in_group("hazard"):
		_shake(0.6)
		get_tree().call_group("hud", "lose_life")`;
  }

  /* ─────────── Rust / WASM sim core ─────────── */
  function genRust(plan) {
    return `// ${plan.title} — deterministic sim core (compiles to wasm32-unknown-unknown)
// cargo build --target wasm32-unknown-unknown --release
#![crate_type = "cdylib"]

pub const SEED: u64 = ${plan.seed >>> 0};
pub const STEP_MS: u64 = 16;
pub const WAVES: u32 = ${plan.numbers.waves};

/// xorshift64* — bit-identical on every platform (crucial for rollback netcode).
pub struct Rng(pub u64);
impl Rng {
    #[inline]
    pub fn next_f32(&mut self) -> f32 {
        self.0 ^= self.0 >> 12; self.0 ^= self.0 << 25; self.0 ^= self.0 >> 27;
        ((self.0.wrapping_mul(0x2545_F491_4F6C_DD1D)) >> 11) as f32 / (1u32 << 21) as f32
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct Entity { pub x: f32, pub y: f32, pub vx: f32, pub vy: f32, pub hp: i16, pub kind: u8 }

pub struct World { pub ents: Vec<Entity>, pub tick: u64, pub score: u32, pub rng: Rng }

impl World {
    pub fn new() -> Self {
        let mut w = World { ents: Vec::with_capacity(512), tick: 0, score: 0, rng: Rng(SEED) };
        w.spawn_wave(1); w
    }

    pub fn spawn_wave(&mut self, wave: u32) {
        let n = 6 + wave * 2;
        for _ in 0..n {
            self.ents.push(Entity {
                x: 40.0 + self.rng.next_f32() * 880.0,
                y: -30.0 - self.rng.next_f32() * 230.0,
                vx: 0.0, vy: 58.0 + wave as f32 * 7.0,
                hp: if self.rng.next_f32() > 0.82 { 3 } else { 1 },
                kind: 1,
            });
        }
    }

    /// One fixed step. dt is deliberately NOT a parameter: determinism lock.
    pub fn step(&mut self) {
        let dt = STEP_MS as f32 / 1000.0;
        self.tick += 1;
        for e in self.ents.iter_mut() {
            e.x += e.vx * dt; e.y += e.vy * dt;
            if e.y > 580.0 { e.y = -40.0; e.x = 40.0 + self.rng.next_f32() * 880.0; }
        }
        self.ents.retain(|e| e.hp > 0);
    }

    pub fn circle_hit(a: &Entity, bx: f32, by: f32, r: f32) -> bool {
        let (dx, dy) = (a.x - bx, a.y - by);
        dx * dx + dy * dy < r * r
    }
}

#[cfg(target_arch = "wasm32")]
mod ffi {
    use super::*;
    #[no_mangle] pub extern "C" fn world_step(ptr: *mut World) { unsafe { (*ptr).step() } }
    #[no_mangle] pub extern "C" fn world_score(ptr: *mut World) -> u32 { unsafe { (*ptr).score } }
}`;
  }

  /* ─────────── Lua modding API ─────────── */
  function genLua(plan) {
    return `--[[ ${plan.title} — mod script (arcgen-modapi v1)
     Mods run in a sandboxed Lua VM; they may register hooks but never
     touch the filesystem or network. ]]

local MOD = {
  id      = "${plan.slug}.mod",
  name    = "${plan.title} // chaos pack",
  version = "1.0.0",
  seed    = ${plan.seed >>> 0}
}

local rng = require("arcgen.rng").new(MOD.seed)

function MOD:on_wave_start(ctx)
  local extra = math.floor(ctx.wave * rng:range(0.4, 1.6))
  ctx.log("spawning " .. extra .. " bonus drones")
  for i = 1, extra do
    ctx.spawn("drone", {
      x      = rng:range(40, ctx.bounds.w - 40),
      y      = -rng:range(20, 240),
      vy     = 60 + ctx.wave * 7 + rng:range(-8, 22),
      hue    = i % #ctx.palette,
      onDeath = function(e)
        ctx.score.add(e.big and 150 or 50)
        ctx.fx.shake(e.big and 8 or 3)
        ctx.fx.burst(e.x, e.y, ctx.palette[e.hue], 18)
      end
    })
  end
end

function MOD:on_player_hit(ctx, dmg)
  if ctx.player.i_frames > 0 then return 0 end
  ctx.audio.blip(90, 0.3, "saw")
  return dmg
end

function MOD:update(ctx, dt)
  -- slow-mo grace window right after taking damage
  if ctx.state.lastHit and (ctx.time - ctx.state.lastHit) < 0.35 then
    ctx.timeScale = 0.55
  else
    ctx.timeScale = 1.0
  end
end

return MOD`;
  }

  /* ─────────── GLSL post shader ─────────── */
  function genShader(plan) {
    return `// ${plan.title} — crt.glsl · bloom + palette quantise + barrel distortion
// Fragment stage only; expects tDiffuse (linear RGBA), uniform vec2 uRes, float uTime.
precision highp float;

uniform sampler2D tDiffuse;
uniform vec2  uRes;
uniform float uTime;
uniform float uCurvature;   // 0.06 typical CRT
uniform float uScanStrength;// 0.25 typical

const vec3 PAL[4] = vec3[4](
${plan.palette.map(glslvec).map((s, i) => '  ' + s + (i < 3 ? ',' : '')).join('\n')}
);

float hash(vec2 p){ return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }

vec2 barrel(vec2 uv, float k){
  vec2 c = uv * 2.0 - 1.0;
  float r2 = dot(c, c);
  return (c * (1.0 + k * r2)) * 0.5 + 0.5;
}

vec3 quantise(vec3 col){
  float best = 1e9; vec3 outc = col;
  for (int i = 0; i < 4; i++){
    float d = distance(col, PAL[i]);
    if (d < best){ best = d; outc = PAL[i]; }
  }
  return mix(col, outc, 0.28);   // keep some fidelity
}

void main(){
  vec2 uv = barrel(gl_FragCoord.xy / uRes, uCurvature);
  if (uv.x < 0.0 || uv.x > 1.0 || uv.y < 0.0 || uv.y > 1.0){
    gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0); return;
  }

  vec3 base = texture2D(tDiffuse, uv).rgb;

  // cheap 5-tap bloom on bright pixels only
  vec3 glow = vec3(0.0);
  for (int i = -2; i <= 2; i++)
    for (int j = -2; j <= 2; j++) {
      vec3 s = texture2D(tDiffuse, uv + vec2(float(i), float(j)) * 2.5 / uRes).rgb;
      glow += max(s - 0.62, 0.0);
    }
  glow /= 25.0;

  // phosphor mask + scanlines
  float line = sin(uv.y * uRes.y * 3.14159) * 0.5 + 0.5;
  vec3 mask = vec3(1.0);
  int slot = int(mod(gl_FragCoord.x, 3.0));
  mask[slot]     *= 1.18;
  mask[(slot + 1) % 3] *= 0.86;

  vec3 col = base + glow * 1.9;
  col *= mix(vec3(1.0), vec3(line), uScanStrength);
  col *= mask;
  col = quantise(col);
  col += (hash(uv * uRes + uTime) - 0.5) * 0.035;      // grain
  col *= smoothstep(1.25, 0.35, length(uv * 2.0 - 1.0)); // vignette

  gl_FragColor = vec4(pow(max(col, 0.0), vec3(0.92)), 1.0);
}`;
  }

  /* ─────────── data tables ─────────── */
  function genTables(plan) {
    const r = R(plan.seed ^ 0x51ed);
    const rows = [];
    for (let w = 1; w <= plan.numbers.waves; w++) {
      rows.push({
        wave: w,
        count: 6 + w * 2,
        speed: Math.round(58 + w * 7),
        hpMix: +(0.1 + w * 0.03).toFixed(2),
        dropChance: +(0.12 - w * 0.004).toFixed(3),
        scoreMult: +(1 + (w - 1) * 0.15).toFixed(2)
      });
    }
    return JSON.stringify({
      meta: { game: plan.slug, seed: plan.seed >>> 0, note: 'edit values here — runtime reads this table, no recompile needed' },
      difficultyCurve: rows,
      powerups: [
        { id: 'spread', weight: Math.round(r() * 40 + 30), duration: 8, color: plan.palette[2] },
        { id: 'life',   weight: Math.round(r() * 20 + 10), duration: 0, color: plan.palette[3] || plan.palette[0] }
      ],
      feel: {
        coyoteTime: 0.12, jumpBuffer: 0.1, hitStop: 0.05,
        shakeDecay: 0.0015, maxShake: 22, iFrames: 1.4
      },
      audio: { master: 0.6, blips: { shoot: [620, 'square', 0.05], hit: [300, 'sawtooth', 0.05], kill: [120, 'sawtooth', 0.22], wave: [520, 'triangle', 0.16] } }
    }, null, 2);
  }

  function genManifest(plan) {
    return JSON.stringify({
      name: plan.title, short_name: plan.title.slice(0, 12), id: plan.slug,
      start_url: 'index.html', display: 'fullscreen', orientation: 'landscape',
      background_color: '#060a13', theme_color: plan.palette[0],
      description: plan.brief, categories: ['games', plan.genre],
      icons: [{ src: 'assets/icon.svg', sizes: 'any', type: 'image/svg+xml' }],
      arcgen: { seed: plan.seed >>> 0, model: Arc.State.SPEC.model, personaDigest: plan.personaDigest }
    }, null, 2);
  }

  function genIcon(plan) {
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <rect width="512" height="512" rx="96" fill="#060a13"/>
  <g stroke="${plan.palette[0]}" stroke-width="10" fill="none" opacity=".35">
    <path d="M64 128h384M64 256h384M64 384h384M128 64v384M256 64v384M384 64v384"/>
  </g>
  <polygon points="256,120 340,300 256,258 172,300" fill="${plan.palette[1]}"/>
  <circle cx="256" cy="352" r="26" fill="${plan.palette[2]}"/>
  <circle cx="256" cy="352" r="46" fill="none" stroke="${plan.palette[2]}" stroke-width="6" opacity=".5"/>
</svg>`;
  }

  function genReadme(plan) {
    return `# ${plan.title}
Autogenerated by **ARCGEN** — offline game-dev agent (\`seed ${plan.seed >>> 0}\`, target \`${plan.lang}\`).

## Play it
\`\`\`bash
# option A — just open it
open index.html            # macOS
xdg-open index.html        # linux

# option B — local server (recommended for save-state + audio unlock)
python3 -m http.server 8080   # then visit http://localhost:8080
\`\`\`

## Controls
| action | input |
|---|---|
| move | \`W A S D\` / arrows / drag |
| fire | \`SPACE\` / click-hold |
| pause | \`P\` |
| retry | \`R\` (after game over) |

## Layout
\`\`\`
${treeText()}
\`\`\`

## Tuning without touching code
Edit \`data/tables.json\` (difficulty curve, powerup weights, feel constants)
and the \`CFG\` block at the top of \`js/game.js\`. The sim is a fixed 1/60 s
timestep with a seeded RNG, so any change is reproducible.

## Ports
The \`ports/\` folder mirrors the design in Unity (C#), Unreal (C++), Godot
(GDScript), LibGDX (Java), pygame (Python), Rust→WASM, plus a Lua mod hook
and a CRT fragment shader. They are reference implementations of the same
spec — pick the one matching your engine.

## Build provenance
- planner → gdd.md + architecture.json
- coder executor → js/game.js (+ ports)
- file generator → tree below, assets/icon.svg, manifest.webmanifest
- terminal executor → \`npm run build\` / \`make\`
- compiler → syntax + reference + budget validation (0 errors required)

No network calls, no telemetry, no external assets. MIT-ish: yours to ship.`;
  }

  function genPackageJSON(plan) {
    return JSON.stringify({
      name: plan.slug, version: '1.0.0', private: true,
      description: plan.brief.slice(0, 120),
      scripts: {
        dev: 'npx --yes serve . -l 8080',
        build: 'node tools/build.js',
        test: 'node tools/selftest.js',
        lint: 'node --check js/game.js && echo "lint ok"'
      },
      keywords: ['game', plan.genre, 'arcgen', 'canvas', 'offline'],
      license: 'MIT'
    }, null, 2);
  }

  /* The two emitted Node scripts contain regex literals. They are stored as
     plain strings (never interpolated) to keep escaping unambiguous. */
  const BUILD_JS = String.raw`// tools/build.js — strips comments, collapses whitespace, reports size vs budget.
const fs = require('fs'), path = require('path');
const SRC = path.join(__dirname, '..', 'js', 'game.js');
const OUT = path.join(__dirname, '..', 'dist', 'game.min.js');

let src = fs.readFileSync(SRC, 'utf8');
const before = Buffer.byteLength(src);
src = src.replace(/\/\*[\s\S]*?\*\//g, '')          // block comments
         .replace(/^\s*\/\/.*$/gm, '')              // line comments
         .replace(/^[ \t]+/gm, '')                  // leading indent
         .replace(/\n{2,}/g, '\n');                 // blank runs
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, src);
const after = Buffer.byteLength(src);
console.log('build: ' + before + ' B -> ' + after + ' B (' + (100 - after / before * 100).toFixed(1) + '% lighter)');
if (after / 1024 > BUDGET_KB) console.warn('WARN: bundle exceeds ' + BUDGET_KB + 'KB budget');
else console.log('budget ok: ' + (after / 1024).toFixed(1) + 'KB / ' + BUDGET_KB + 'KB');
`;

  const SELFTEST_JS = String.raw`// tools/selftest.js — static verification of the generated runtime.
// node tools/selftest.js   → exit 0 means the build is shippable.
const fs = require('fs'), path = require('path');
const src = fs.readFileSync(path.join(__dirname, '..', 'js', 'game.js'), 'utf8');
const has = s => new RegExp(s, 'm').test(src);

const checks = [
  ['balanced braces',    () => (src.match(/{/g) || []).length === (src.match(/}/g) || []).length],
  ['balanced parens',    () => (src.match(/\(/g) || []).length === (src.match(/\)/g) || []).length],
  ['fixed timestep',     () => has('STEP: 1 / 60')],
  ['seeded rng',         () => has('0x6D2B79F5')],
  ['no network egress',  () => !has('fetch\\(|XMLHttpRequest|WebSocket|https?:')],
  ['no dynamic eval',    () => !has('eval\\(|new Function\\(')],
  ['rAF driver',         () => has('requestAnimationFrame')],
  ['keyboard input map', () => has("addEventListener\\('keydown'")],
  ['pointer + touch',    () => has('touchstart')],
  ['win state',          () => has('endRun\\(true\\)')],
  ['lose state',         () => has('endRun\\(false\\)')],
  ['high-score persist', () => has('localStorage')],
  ['audio synth',        () => has('AudioContext')],
  ['particle fx',        () => has('function boom')]
];

let fail = 0;
for (const [name, fn] of checks) {
  let ok = false;
  try { ok = !!fn(); } catch (e) { ok = false; }
  console.log((ok ? '  PASS  ' : '  FAIL  ') + name);
  if (!ok) fail++;
}
console.log(fail ? '\n' + fail + ' check(s) failed' : '\nall ' + checks.length + ' checks passed - build is shippable');
process.exit(fail ? 1 : 0);
`;

  function genBuildTools(plan) {
    return BUILD_JS.replace('BUDGET_KB', String(plan.budget.bundleKb));
  }
  function genSelfTest() { return SELFTEST_JS; }

  function genMakefile(plan) {
    return `# ${plan.title} — build automation
CC      ?= cc
CXX     ?= g++
PY      ?= python3
WASM_RS ?= wasm-pack

.PHONY: all serve lint build test clean web native wasm

all: lint build test

serve:
	$(PY) -m http.server 8080

lint:
	node --check js/game.js
	@echo "[lint] js ok"

build:
	node tools/build.js

test:
	node tools/selftest.js

# --- optional native targets -------------------------------------
native:
	$(CXX) -std=c++20 -O2 -Iinclude ports/engine/${plan.slug}-actor.cpp -o build/${plan.slug}-sim

wasm:
	cd rust && $(WASM_RS) build --release --target wasm32-unknown-unknown

clean:
	rm -rf dist build/*.o
`;
  }

  function genGitignore() {
    return `node_modules/
dist/
build/
*.log
.DS_Store
.vscode/
.idea/
.cache/
`;
  }

  /* ─────────── helpers ─────────── */
  function hex2unity(h) {
    const n = h.slice(1).match(/../g).map(x => (parseInt(x, 16) / 255).toFixed(3));
    return `new Color(${n[0]}f, ${n[1]}f, ${n[2]}f, 1f)`;
  }
  function pycolor(h) { return '(' + h.slice(1).match(/../g).map(x => parseInt(x, 16)).join(', ') + ')'; }
  function godotcolor(h) { const n = h.slice(1).match(/../g).map(x => (parseInt(x, 16) / 255).toFixed(3)); return `Color(${n.join(', ')})`; }
  function glslvec(h) { const n = h.slice(1).match(/../g).map(x => (parseInt(x, 16) / 255).toFixed(3)); return `vec3(${n.join(', ')})`; }
  function className(s) { return s.replace(/[^A-Za-z0-9]/g, ''); }

  /* Static project layout — README/tree must not call filesFor() (recursion). */
  const TREE = [
    'index.html', 'css/hud.css', 'js/game.js', 'gdd.md', 'architecture.json',
    'data/tables.json', 'assets/icon.svg', 'manifest.webmanifest', 'README.md',
    'package.json', 'Makefile', '.gitignore', 'tools/build.js', 'tools/selftest.js',
    'shader/crt.glsl', 'mods/chaos.lua',
    'ports/unity/PlayerController.cs', 'ports/unreal/UfoPawn.cpp',
    'ports/godot/player.gd', 'ports/libgdx/<Game>.java', 'ports/pygame/main.py',
    'ports/rust/src/lib.rs'
  ];

  function treeText() { return TREE.map(p => '  ' + p).join('\n'); }

  /* ─────────── extra stack modules (per-language companions) ─────────── */

  /* C++ native SDL2 build — emitted whenever 'cpp' joins the stack. */
  function genNativeMain(plan) {
    const P = plan.palette;
    return `/* ${plan.title} — native SDL2/OpenGL ES mirror of the JS runtime.
 * Generated by ARCGEN · seed ${plan.seed >>> 0} · deterministic fixed step.
 * Build: cmake -S native -B build && cmake --build build
 */
#include <SDL2/SDL.h>
#include <cmath>
#include <cstdio>
#include <vector>
#include <array>

namespace cfg {
  constexpr int   W = ${960}, H = ${540};
  constexpr float STEP = 1.0f / 60.0f;
  constexpr int   WAVES = ${Math.max(3, Math.min(20, plan.numbers.waves))};
  constexpr std::array<unsigned, 4> PAL = { 0x${P[0].slice(1)}u, 0x${(P[1] || P[0]).slice(1)}u, 0x${(P[2] || P[0]).slice(1)}u, 0x${(P[3] || P[0]).slice(1)}u };
}

struct Entity { float x, y, vx, vy, r; int hp; unsigned col; };

static uint32_t g_seed = ${plan.seed >>> 0}u;
static inline float rnd() {                       /* mulberry32 — matches JS core */
  g_seed += 0x6D2B79F5u; uint32_t t = g_seed;
  t = (t ^ (t >> 15)) * (t | 1u);
  t ^= t + ((t ^ (t >> 7)) * (t | 61u));
  return ((t ^ (t >> 14)) & 0x7fffff) / 8388608.0f;
}

int main(int, char**) {
  if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO) != 0) { std::printf("sdl init failed\\n"); return 1; }
  SDL_Window* win = SDL_CreateWindow("${plan.title}", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, cfg::W, cfg::H, SDL_WINDOW_SHOWN);
  SDL_Renderer* ren = SDL_CreateRenderer(win, -1, SDL_RENDERER_ACCELERATED);
  std::vector<Entity> enemies;
  for (int i = 0; i < 6 + cfg::WAVES * 2; ++i)
    enemies.push_back({ rnd() * cfg::W, rnd() * cfg::H * .4f, 0.f, 60.f + rnd() * 40.f, 12.f, 1, cfg::PAL[i % 4] });

  bool running = true; float acc = 0.f; Uint32 prev = SDL_GetTicks();
  while (running) {
    SDL_Event e; while (SDL_PollEvent(&e)) if (e.window.event == SDL_WINDOWEVENT_CLOSE) running = false;
    float now = SDL_GetTicks() / 1000.f; acc += now - prev; prev = now;
    while (acc >= cfg::STEP) {                    /* fixed timestep determinism lock */
      for (auto& en : enemies) { en.y += en.vy * cfg::STEP; en.x += std::cos(en.y * .02f) * 40.f * cfg::STEP;
        if (en.y > cfg::H + 40.f) { en.y = -40.f; en.x = rnd() * cfg::W; } }
      acc -= cfg::STEP;
    }
    SDL_SetRenderDrawColor(ren, 6, 10, 19, 255); SDL_RenderClear(ren);
    for (const auto& en : enemies) {
      SDL_SetRenderDrawColor(ren, (en.col >> 16) & 0xff, (en.col >> 8) & 0xff, en.col & 0xff, 255);
      SDL_Rect rc { (int)(en.x - en.r), (int)(en.y - en.r), (int)(en.r * 2), (int)(en.r * 2) };
      SDL_RenderFillRect(ren, &rc);
    }
    SDL_RenderPresent(ren);
    SDL_Delay(1);
  }
  SDL_DestroyRenderer(ren); SDL_DestroyWindow(win); SDL_Quit();
  return 0;
}
`;
  }

  function genCMake(plan) {
    return `# ${plan.title} — native target generated by ARCGEN
cmake_minimum_required(VERSION 3.16)
project(${className(plan.title)}Native LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(SDL2 REQUIRED)
add_executable(${className(plan.title).toLowerCase()} main.cpp)
target_include_directories(${className(plan.title).toLowerCase()} PRIVATE \${SDL2_INCLUDE_DIRS})
target_link_libraries(${className(plan.title).toLowerCase()} \${SDL2_LIBRARIES} m)
`;
  }

  /* Java console harness — compiles with plain javac, zero deps. */
  function genJavaHarness(plan) {
    return `// ${plan.title} — headless tuning harness (plain javac, no dependencies).
// Mirrors the CFG block of js/game.js so designers can validate numbers in JVM.
public class ArcGen {
    static final int W = 960, H = 540;
    static final double STEP = 1.0 / 60.0;
    static final int WAVES = ${Math.max(3, Math.min(20, plan.numbers.waves))};
    static final double PLAYER_SPEED = ${Math.round(240 + (plan.seed % 90))};
    static final double FIRE_COOLDOWN = ${(0.13 + (plan.seed % 90) / 1000).toFixed(3)};
    static final String[] PAL = {"${plan.palette.join('", "')}"};

    public static void main(String[] args) {
        System.out.println("${plan.title} tuning snapshot");
        System.out.printf("waves=%d speed=%.0f cd=%.3f pal=%s%n", WAVES, PLAYER_SPEED, FIRE_COOLDOWN, String.join(" ", PAL));
        long s = ${plan.seed >>> 0}L;                       // mulberry32 — same stream as JS core
        for (int i = 0; i < 5; i++) {
            s = (s + 0x6D2B79F5L) & 0xFFFFFFFFL;
            long t = s; t = (t ^ (t >>> 15)) * (t | 1); t = (t + ((t ^ (t >>> 7)) * (t | 61))) & 0xFFFFFFFFL;
            System.out.printf("rnd[%d] = %.4f%n", i, ((t ^ (t >>> 14)) & 0xFFFFFFFFL) / 4294967296.0);
        }
    }
}
`;
  }

  /* Python tooling — validates data/tables.json offline. */
  function genPyTool(plan) {
    return `#!/usr/bin/env python3
"""${plan.title} — data-table validator (stdlib only, runs anywhere).
Usage: python3 tools/tuning_tool.py data/tables.json
"""
import json
import sys

EXPECTED_KEYS = ["difficultyCurve", "powerups", "feel"]

def check(path: str) -> int:
    with open(path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    missing = [k for k in EXPECTED_KEYS if k not in data]
    if missing:
        print("FAIL missing keys:", ", ".join(missing))
        return 1
    rows = data["difficultyCurve"]
    bad = [w for w in rows if w.get("count", 0) <= 0 or w.get("speed", 0) <= 0]
    if bad:
        print("FAIL", len(bad), "wave rows have non-positive count/speed")
        return 1
    print(f"OK {path}: {len(rows)} wave rows, palette-driven feel block present")
    return 0

if __name__ == "__main__":
    sys.exit(check(sys.argv[1] if len(sys.argv) > 1 else "data/tables.json"))
`;
  }

  function genCargoToml(plan) {
    return `[package]
name = "${plan.slug.replace(/-/g, '_')}"
version = "0.1.0"
edition = "2021"
description = "${plan.title} deterministic sim core (ARCGEN generated)"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"
lto = true
`;
  }

  function genUnityMeta(plan) {
    return `{
  "folder": "Assets/${className(plan.title)}",
  "generator": "ARCGEN",
  "seed": ${plan.seed >>> 0},
  "notes": "Import ports/unity/PlayerController.cs into this folder. Colours below are linear-space conversions of the runtime palette.",
  "colors": {
${plan.palette.map((c, i) => `    "pal_${i}": "${hex2unity(c).replace('new Color', '').trim()}"`).join(',\n')}
  },
  "tags": ["${plan.genre}", "${plan.view}-view", "arcgen"],
  "physics": { "gravityScale": 1.0, "fixedDeltaTime": 0.0166667 }
}
`;
  }

  function genGodotProject(plan) {
    return `; Godot 4 project scaffold for ${plan.title} (generated by ARCGEN)
; Open in Godot 4 and attach ports/godot/player.gd to the Player node.
[project]
config/name="${plan.title}"
config/version="${(plan.seed % 5) + 1}.0"
run/main_scene=""
config/features=PackedStringArray("4.2")

[input]
move_left={
"deadzone": 0.2,
"events": [ "KeyA", "KeyLeft" ]
}
move_right={
"deadzone": 0.2,
"events": [ "KeyD", "KeyRight" ]
}
fire={
"deadzone": 0.2,
"events": [ "Space", "MouseButtonLeft" ]
}

[rendering]
environment/defaults/default_clear_color=Color(0.024, 0.039, 0.075, 1)
`;
  }

  function genLuaConfig(plan) {
    return `-- ${plan.title} — mod configuration consumed by mods/chaos.lua
CONFIG = {
  title     = "${plan.title}",
  seed      = ${plan.seed >>> 0},
  waves     = ${Math.max(3, Math.min(20, plan.numbers.waves))},
  palette   = { ${plan.palette.map(c => `"${c}"`).join(', ')} },
  chaos     = { spawnBias = 1.35, bulletRain = 0.25, gravityFlipChance = 0.05 },
  hooks     = { "on_wave_start", "on_player_hit", "update" },
  version   = "1.0.0"
}
return CONFIG
`;
  }

  function genGLSLBloom(plan) {
    return `/* ${plan.title} bloom pre-pass — pairs with shader/crt.glsl */
precision mediump float;
uniform sampler2D uScene;
uniform vec2  uRes;
uniform float uThresh;
varying vec2 vUv;

void main() {
  vec3 src = texture2D(uScene, vUv).rgb;
  float lum = dot(src, vec3(0.2126, 0.7152, 0.0722));
  vec3 glow = src * smoothstep(uThresh, 1.0, lum);
  vec3 acc = vec3(0.0);
  float wsum = 0.0;
  for (int x = -2; x <= 2; x++) {
    for (int y = -2; y <= 2; y++) {
      vec2 off = vec2(float(x), float(y)) / uRes * 2.0;
      vec3 s = texture2D(uScene, vUv + off).rgb;
      float l = dot(s, vec3(0.2126, 0.7152, 0.0722));
      float w = 1.0 - length(off) * uRes.x * 0.002;
      acc += s * max(0.0, l - uThresh) * w;
      wsum += w;
    }
  }
  vec3 bloom = acc / max(wsum, 1.0) * 1.8;
  gl_FragColor = vec4(glow + bloom + src * 0.15, 1.0);
}
`;
  }

  function genGitlabCI(plan) {
    return `# ${plan.title} — CI pipeline (gitlab-ci compatible syntax)
stages: [validate, compile, test, package]

validate:tables:
  stage: validate
  script:
    - python3 tools/tuning_tool.py data/tables.json

compile:web:
  stage: compile
  script:
    - node tools/build.js

test:selftest:
  stage: test
  script:
    - node tools/selftest.js

package:zip:
  stage: package
  artifacts:
    paths: [build/]
  script:
    - make bundle

compile:native:
  stage: compile
  script:
    - cmake -S native -B build/native && cmake --build build/native
`;
  }

  /* ─────────── assemble the project ─────────── */
  /* Registry: one generator per language-stack member. The file generator
     batch-emits every module whose language is in plan.langs — multiple
     languages at once, many files per pass. */
  const EMITTERS = {
    js:   p => ({ 'js/game.js': genGameJS(p), 'tools/build.js': genBuildTools(p), 'tools/selftest.js': genSelfTest(p) }),
    html: p => ({ 'index.html': genIndexHTML(p), 'manifest.webmanifest': genManifest(p) }),
    css:  p => ({ 'css/hud.css': genHudCSS(p) }),
    json: p => ({ 'data/tables.json': genTables(p), 'architecture.json': genArchJSON(p) }),
    cs:   p => ({ 'ports/unity/PlayerController.cs': genUnityCS(p), 'ports/unity/project.meta': genUnityMeta(p) }),
    cpp:  p => ({ 'ports/unreal/UfoPawn.cpp': genUnrealCPP(p), 'native/main.cpp': genNativeMain(p), 'native/CMakeLists.txt': genCMake(p) }),
    java: p => { const o = {}; o['ports/libgdx/' + className(p.title) + '.java'] = genJava(p); o['java/ArcGen.java'] = genJavaHarness(p); return o; },
    py:   p => ({ 'ports/pygame/main.py': genPython(p), 'tools/tuning_tool.py': genPyTool(p) }),
    gd:   p => ({ 'ports/godot/player.gd': genGDScript(p), 'ports/godot/project.godot': genGodotProject(p) }),
    rs:   p => ({ 'ports/rust/src/lib.rs': genRust(p), 'rust/Cargo.toml': genCargoToml(p) }),
    lua:  p => ({ 'mods/chaos.lua': genLua(p), 'mods/config.lua': genLuaConfig(p) }),
    glsl: p => ({ 'shader/crt.glsl': genShader(p), 'shader/bloom.glsl': genGLSLBloom(p) })
  };
  /* always-on regardless of stack selection */
  const COMMON = p => ({ 'gdd.md': genGDD(p), 'README.md': genReadme(p), 'Makefile': genMakefile(p), '.gitignore': genGitignore(), 'package.json': genPackageJSON(p), '.gitlab-ci.yml': genGitlabCI(p), 'assets/icon.svg': genIcon(p) });

  function filesFor(plan) {
    const f = {};
    Object.assign(f, COMMON(plan));
    const langs = (plan.langs && plan.langs.length) ? plan.langs : [plan.lang || 'js'];
    for (const id of langs) {
      const em = EMITTERS[id];
      if (em) Object.assign(f, em(plan));
    }
    /* the playable web core must exist even if the user deselected it */
    if (!f['js/game.js']) Object.assign(f, EMITTERS.js(plan));
    return f;
  }

  /* primary entry returns full file map for chosen language emphasis */
  function generate(plan, persona) {
    plan.personaDigest = 'sha1:' + (Arc.Planner.hashSeed(persona) >>> 0).toString(16);
    const files = filesFor(plan);
    /* reorder so the requested language leads the tree */
    const wantExt = (Arc.State.LANGS.find(l => l.id === plan.lang) || {}).ext;
    const keys = Object.keys(files).sort((a, b) => {
      const pa = wantExt && a.endsWith(wantExt) ? 0 : 1;
      const pb = wantExt && b.endsWith(wantExt) ? 0 : 1;
      return pa - pb || a.localeCompare(b);
    });
    const ordered = {}; keys.forEach(k => ordered[k] = files[k]);
    return ordered;
  }

  global.Arc = global.Arc || {};
  global.Arc.Generators = { generate, filesFor, EMITTERS };
})(window);
